// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppEigen.h>
#include <Rcpp.h>

using namespace Rcpp;

// dummy_cpp
void dummy_cpp();
RcppExport SEXP rvinecopulib_dummy_cpp() {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    dummy_cpp();
    return R_NilValue;
END_RCPP
}
