# Workflow derived from https://github.com/r-lib/actions/tree/v2/examples
# Need help debugging build failures? Start at https://github.com/r-lib/actions#where-to-find-help
on:
  pull_request:
    branches: [main]

name: revdepcheck

jobs:
  R-CMD-check:
    runs-on: ${{ matrix.config.os }}

    name: ${{ matrix.config.os }} (${{ matrix.config.r }})

    strategy:
      fail-fast: false
      matrix:
        config:
          - {os: macos-latest,   r: 'devel'}
          - {os: windows-latest, r: 'devel'}
          - {os: ubuntu-latest,   r: 'devel'}

    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      R_KEEP_PKG_SOURCE: yes

    steps:
      - uses: actions/checkout@v4

      - uses: r-lib/actions/setup-pandoc@v2

      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: ${{ matrix.config.r }}

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: any::rcmdcheck
          needs: check

      - name: Reverse dependency check
        shell: Rscript {0}
        run: |
          install.packages(c("devtools", "fs"))
          fs::dir_create("../revdeps")
          devtools::build(path = "../revdeps/")
          tools::check_packages_in_dir("../revdeps", reverse = list(which = "all"))
          tools::summarize_check_packages_in_dir_timings("../revdeps")
          tools::summarize_check_packages_in_dir_depends("../revdeps")
          tools::summarize_check_packages_in_dir_results("../revdeps")
